// src/App.jsx
import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import Header from './components/Header';
import Work from './pages/Work';
import Services from './pages/Services';
import Process from './pages/Process';
import About from './pages/About';
import Contact from './pages/Contact';
import Pricing from './pages/Pricing';
import ScrollToTopButton from './components/ScrollToTopButton';

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/" element={<>
          <Header />
          <Work />
          <Services />
          <Process />
          <About />
          <Contact />
          <ScrollToTopButton />
        </>} />
        <Route path="/pricing" element={<Pricing />} />
      </Routes>
    </Router>
  );
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <Header />
    <Home />
    <Work />
    <Services />
    <Process />
  </div>
</template>

<script>
import Header from "../src/layout/Header.vue";
import Home from "../src/views/Home.vue";
import Work from "../src/views/Work.vue";
import Services from "../src/views/Services.vue";
import Process from "../src/views/Process.vue";


export default {
  name: "App",
  components: {
    Header, Home, Work, Services, Process
  },
};
</script>

<style>

</style>
